### ISSUE TITLE
How can I use the plugin for a single element?

### ISSUE THREAD

**Issue by devunion** [noxify/gridsome-remark-classes#1]
Hello,
Does it possible to use the plugin to add class to a single element in markdown file?

I'm trying to center single image on the page. 

As I see, gridsome does not allow to render markdown content inside HTML. Something like that:
```
<p align="center" markdown='1'>![IMG ALT](IMG_SRC)</p>

```

And I can't find any other way to do that. 

P.S. It is possible to use pure HTML code to do that, but I want to keep an ability to use `g-image` for images rendering.

**Comment by noxify** [comment]
Hi @devunion ,

> Does it possible to use the plugin to add class to a single element in markdown file?

I don't think so, but please check the code below, which should solve your problem :)

> As I see, gridsome does not allow to render markdown content inside HTML. Something like that:

If you're working with markdown files, you should be able to use something like this:

```
// DOES NOT WORK
<div align="center" markdown='1'>![IMG ALT](IMG_SRC)</div>

// DOES WORK
<div align="center" markdown='1'>
![IMG ALT](IMG_SRC)
</div>
```

Hope that helps.
